console.log("avanzar");
console.log("rellenar");
console.log("avanzar");
console.log("avanzar");
console.log("rellenar");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("finalizado");
