console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("girar a la izquierda 90°");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("finalizado");
