console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("girar a la izquierda");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("avanzar");
console.log("quitar monticulo");
console.log("finalizado");
